name: postnow
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2

  firebase_core: ^0.4.5
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.15

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  firebase_database: ^3.1.6
  firebase_storage: ^3.1.6

  google_maps_webservice: ^0.0.17
  google_maps_flutter: ^0.5.28+1
  google_map_polyline: ^0.2.0+1
  flutter_google_places: ^0.2.6
  permission_handler: ^5.0.1+1
  geolocator: ^5.3.2+2
  flutter_credit_card: ^0.1.3
  shared_preferences: ^0.5.8
  flutter_braintree: ^1.0.2+2
  camera: ^0.5.8+2
  image_picker: ^0.6.7+4
  path_provider: ^1.6.11
  path: ^1.6.4
  easy_localization: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/marker_buttons/
    - assets/translations/