/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData credit_card_with_add_button = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData klarna__1_ = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData klarna__2_ = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_visa = IconData(0xf1f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_mastercard = IconData(0xf1f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_discover = IconData(0xf1f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_amex = IconData(0xf1f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_paypal = IconData(0xf1f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_stripe = IconData(0xf1f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_alt = IconData(0xf283, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal = IconData(0xf342, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_alt = IconData(0xf3d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_pay = IconData(0xf415, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_apple_pay = IconData(0xf416, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coins = IconData(0xf51e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
