enum MenuTyp {
  FROM_OR_TO,
  NO_DRIVER_AVAILABLE,
  TRY_AGAIN,
  NO_ROUTE,
  CALCULATING_DISTANCE,
  CONFIRM,
  SEARCH_DRIVER,
  PAYMENT_WAITING,
  PAYMENT_DECLINED,
  ACCEPTED,
  PACKAGE_PICKED,
  COMPLETED
}